import { oelsnerStarterPatterns } from './oelsnerPatterns';
import type { PatternBook } from './types';

export const referenceBooks: PatternBook[] = [
  {
    id: 'oelsner',
    title: 'A Handbook of Weaves',
    author: 'G. H. Oelsner',
    year: '1915',
    draftCount: 2257,
    summary:
      'Large structural reference across simple, derivative, and compound weaves. This first pass includes a curated starter shelf of common Oelsner weave families that load directly into the editor.',
    sourceLabel: 'Open Library 1915 edition',
    referenceUrl: 'https://openlibrary.org/books/OL7070771M/A_handbook_of_weaves',
    access: 'public-domain',
    tags: ['reference', 'twill', 'compound'],
    note:
      'Curated starter reconstructions are grounded in the 1915 public-domain Oelsner book and labeled by chapter page so users can read the source context.',
    patterns: oelsnerStarterPatterns,
  },
  {
    id: 'kastanek',
    title: 'A Manual of Weave Construction',
    author: 'Ivo Kastanek',
    year: '1903 / 1914',
    draftCount: 517,
    summary:
      'Systematic foundation and derivative weave book that maps well to a book-first browsing workflow.',
    sourceLabel: 'Public-domain reference',
    access: 'public-domain',
    tags: ['foundation weaves', 'teaching', 'reference'],
    note: 'Book cataloged for local indexing, but pattern-by-pattern extraction is not bundled yet.',
    patterns: [],
  },
  {
    id: 'posselt',
    title: 'A Dictionary of Weaves',
    author: 'Emmanuel Anthony Posselt',
    year: '1914',
    draftCount: 1886,
    summary:
      'Dense 4- to 9-harness draft dictionary with a strong classification angle and a large pattern inventory.',
    sourceLabel: 'Catalog reference',
    access: 'catalog',
    tags: ['dictionary', '4 shafts', '8 shafts'],
    note: 'Cataloged as a source book. Pattern extraction should happen from a licensed or public-domain copy.',
    patterns: [],
  },
  {
    id: 'jansen',
    title: 'Revised Textile Design Book',
    author: 'Emil Jansen',
    year: '1898',
    draftCount: 1723,
    summary:
      'Historic design book with many draft plates that fits a page-indexed import pipeline well.',
    sourceLabel: 'Public-domain reference',
    access: 'public-domain',
    tags: ['design plates', 'historic', 'pattern book'],
    note: 'Book metadata is present. Pattern indexing should be done locally from a source scan.',
    patterns: [],
  },
  {
    id: 'serrure',
    title: 'Atlas de 4000 Armures',
    author: 'Louis Serrure',
    year: 'circa 1920',
    draftCount: 3212,
    summary:
      'Massive French weave atlas with a strong “browse by book, then by pattern” fit.',
    sourceLabel: 'Catalog reference',
    access: 'catalog',
    tags: ['atlas', 'french', 'large collection'],
    note: 'Source book is cataloged, but the extracted pattern library is not bundled in the repo.',
    patterns: [],
  },
  {
    id: 'fressinet',
    title: "Atlas D'Armures Textiles",
    author: 'B. Fressinet',
    year: '1905',
    draftCount: 2904,
    summary:
      'Large French atlas with a rich range of structural drafting material.',
    sourceLabel: 'Catalog reference',
    access: 'catalog',
    tags: ['atlas', 'french', 'historic'],
    note: 'Prepared as a catalog entry for future local indexing.',
    patterns: [],
  },
  {
    id: 'morath',
    title: "A German Weaver's Pattern Book, 1784 - 1810",
    author: 'Christian Morath, Joseph Murllman, and others',
    year: '1784-1810',
    draftCount: 297,
    summary:
      'Hand-penned manuscript drafts with strong archival value for a source-book shelf.',
    sourceLabel: 'Catalog reference',
    access: 'catalog',
    tags: ['manuscript', 'historic', 'german'],
    note: 'Best handled as a locally indexed manuscript source rather than a repo-bundled pattern dump.',
    patterns: [],
  },
  {
    id: 'thaller',
    title: 'Thaller Manuscript Drafts',
    author: 'Johann Georg Thaller and later contributors',
    year: '1748',
    draftCount: 128,
    summary:
      'Manuscript-based collection suitable for an archive-driven explore shelf.',
    sourceLabel: 'Catalog reference',
    access: 'catalog',
    tags: ['manuscript', 'archive', 'historic'],
    note: 'Catalog metadata only for now.',
    patterns: [],
  },
  {
    id: 'watson',
    title: 'Textile Design and Colour',
    author: 'William Watson',
    year: '1912',
    draftCount: 1096,
    summary:
      'Broad weave and color reference that aligns especially well with the draft color editor.',
    sourceLabel: 'Public-domain reference',
    access: 'public-domain',
    tags: ['color', 'reference', 'historic'],
    note: 'Good candidate for a color-focused local indexing pass.',
    patterns: [],
  },
  {
    id: 'ashenhurst',
    title: 'An Album of Textile Designs',
    author: 'Thomas R. Ashenhurst',
    year: '1881',
    draftCount: 7000,
    summary:
      'Classic textile design volume known for a very large pattern inventory.',
    sourceLabel: 'Public-domain reference',
    access: 'public-domain',
    tags: ['7000 patterns', 'design reference', 'historic'],
    note: 'Too large to bundle manually; best handled with a local ingest/index pipeline.',
    patterns: [],
  },
];
