import { normalizeDraft } from './draft';
import type { BookPatternEntry } from './types';

export const oelsnerStarterPatterns: BookPatternEntry[] = [
  {
    id: 'oe-p014-plain-weave',
    title: 'Plain Weave',
    referenceCode: 'OEL-P014',
    referencePage: 'p. 14',
    summary: 'Starter reconstruction for the plain weave chapter in Oelsner.',
    tags: ['oelsner', 'plain weave', 'starter'],
    status: 'loadable',
    note: 'Curated starter reconstruction based on the Oelsner plain-weave chapter.',
    draft: normalizeDraft({
      version: 1,
      sourceType: 'manual',
      shaftCount: 4,
      treadleCount: 4,
      threading: [1, 2, 3, 4, 1, 2, 3, 4],
      tieUp: [
        [true, false, true, false],
        [false, true, false, true],
        [true, false, true, false],
        [false, true, false, true],
      ],
      treadling: [1, 2, 1, 2, 1, 2, 1, 2],
      warpColors: ['#f1ead9'],
      weftColors: ['#8f5136'],
      parseConfidence: 1,
      warnings: [],
      title: 'Oelsner Plain Weave',
      sourceLabel: 'A Handbook of Weaves',
    }),
  },
  {
    id: 'oe-p016-22-twill',
    title: '2/2 Twill',
    referenceCode: 'OEL-P016',
    referencePage: 'p. 16',
    summary: 'Starter reconstruction for the twill chapter in Oelsner.',
    tags: ['oelsner', 'twill', 'starter'],
    status: 'loadable',
    note: 'Curated starter reconstruction based on the Oelsner twill chapter.',
    draft: normalizeDraft({
      version: 1,
      sourceType: 'manual',
      shaftCount: 4,
      treadleCount: 4,
      threading: [1, 2, 3, 4, 1, 2, 3, 4],
      tieUp: [
        [true, false, false, true],
        [true, true, false, false],
        [false, true, true, false],
        [false, false, true, true],
      ],
      treadling: [1, 2, 3, 4, 1, 2, 3, 4],
      warpColors: ['#f6ebda'],
      weftColors: ['#c46538'],
      parseConfidence: 1,
      warnings: [],
      title: 'Oelsner 2/2 Twill',
      sourceLabel: 'A Handbook of Weaves',
    }),
  },
  {
    id: 'oe-p026-five-end-satin',
    title: '5-End Satin',
    referenceCode: 'OEL-P026',
    referencePage: 'p. 26',
    summary: 'Starter reconstruction for the satin chapter in Oelsner.',
    tags: ['oelsner', 'satin', 'starter'],
    status: 'loadable',
    note: 'Curated starter reconstruction based on the Oelsner satin chapter.',
    draft: normalizeDraft({
      version: 1,
      sourceType: 'manual',
      shaftCount: 5,
      treadleCount: 5,
      threading: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
      tieUp: [
        [true, false, false, false, false],
        [false, false, true, false, false],
        [false, false, false, false, true],
        [false, true, false, false, false],
        [false, false, false, true, false],
      ],
      treadling: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
      warpColors: ['#f5eee1'],
      weftColors: ['#b75a2c'],
      parseConfidence: 1,
      warnings: [],
      title: 'Oelsner 5-End Satin',
      sourceLabel: 'A Handbook of Weaves',
    }),
  },
  {
    id: 'oe-p043-basket-weave',
    title: 'Basket Weave',
    referenceCode: 'OEL-P043',
    referencePage: 'p. 43',
    summary: 'Grouped over-under blocks for the basket-weave family in Oelsner.',
    tags: ['oelsner', 'basket', 'starter'],
    status: 'loadable',
    note: 'Curated starter reconstruction based on the Oelsner basket-weave chapter.',
    draft: normalizeDraft({
      version: 1,
      sourceType: 'manual',
      shaftCount: 4,
      treadleCount: 4,
      threading: [1, 1, 2, 2, 3, 3, 4, 4],
      tieUp: [
        [true, false, false, false],
        [true, false, false, false],
        [false, true, false, false],
        [false, true, false, false],
      ],
      treadling: [1, 1, 2, 2, 1, 1, 2, 2],
      warpColors: ['#e8dbc2'],
      weftColors: ['#8d4c33'],
      parseConfidence: 1,
      warnings: [],
      title: 'Oelsner Basket Weave',
      sourceLabel: 'A Handbook of Weaves',
    }),
  },
  {
    id: 'oe-p046-warp-rib',
    title: 'Warp Rib',
    referenceCode: 'OEL-P046',
    referencePage: 'p. 46',
    summary: 'Warp-dominant rib structure from the rib-weave family in Oelsner.',
    tags: ['oelsner', 'rib', 'warp rib'],
    status: 'loadable',
    note: 'Curated starter reconstruction based on the Oelsner rib-weave chapter.',
    draft: normalizeDraft({
      version: 1,
      sourceType: 'manual',
      shaftCount: 4,
      treadleCount: 4,
      threading: [1, 1, 2, 2, 3, 3, 4, 4],
      tieUp: [
        [true, false, false, false],
        [false, false, true, false],
        [false, true, false, false],
        [false, false, false, true],
      ],
      treadling: [1, 1, 1, 2, 2, 2, 3, 3],
      warpColors: ['#efe7d7'],
      weftColors: ['#975737'],
      parseConfidence: 1,
      warnings: [],
      title: 'Oelsner Warp Rib',
      sourceLabel: 'A Handbook of Weaves',
    }),
  },
  {
    id: 'oe-p144-pointed-twill',
    title: 'Pointed Twill',
    referenceCode: 'OEL-P144',
    referencePage: 'p. 144',
    summary: 'A herringbone-style pointed twill reconstruction from the Oelsner pointed-twill family.',
    tags: ['oelsner', 'pointed twill', 'herringbone'],
    status: 'loadable',
    note: 'Curated starter reconstruction based on the Oelsner herringbone or pointed-twill chapter.',
    draft: normalizeDraft({
      version: 1,
      sourceType: 'manual',
      shaftCount: 4,
      treadleCount: 4,
      threading: [1, 2, 3, 4, 3, 2, 1, 2, 3, 4, 3, 2],
      tieUp: [
        [true, false, false, true],
        [true, true, false, false],
        [false, true, true, false],
        [false, false, true, true],
      ],
      treadling: [1, 2, 3, 4, 3, 2, 1, 2, 3, 4, 3, 2],
      warpColors: ['#f2e6d7'],
      weftColors: ['#a85f3a'],
      parseConfidence: 1,
      warnings: [],
      title: 'Oelsner Pointed Twill',
      sourceLabel: 'A Handbook of Weaves',
    }),
  },
  {
    id: 'oe-p082-broken-twill',
    title: 'Broken Twill',
    referenceCode: 'OEL-P082',
    referencePage: 'p. 82',
    summary: 'A starter broken-twill reconstruction inspired by Oelsner’s reversed and broken twill sections.',
    tags: ['oelsner', 'broken twill', 'reversed twill'],
    status: 'loadable',
    note: 'Curated starter reconstruction based on the Oelsner broken or reversed twill family.',
    draft: normalizeDraft({
      version: 1,
      sourceType: 'manual',
      shaftCount: 4,
      treadleCount: 4,
      threading: [1, 2, 3, 4, 2, 1, 3, 4, 2, 1, 3, 4],
      tieUp: [
        [true, false, false, true],
        [true, true, false, false],
        [false, true, true, false],
        [false, false, true, true],
      ],
      treadling: [1, 2, 3, 4, 2, 1, 3, 4, 2, 1, 3, 4],
      warpColors: ['#f0e7da'],
      weftColors: ['#b36d44'],
      parseConfidence: 1,
      warnings: [],
      title: 'Oelsner Broken Twill',
      sourceLabel: 'A Handbook of Weaves',
    }),
  },
];
