import { normalizeDraft } from './draft';
import type { PresetDefinition } from './types';

export const presets: PresetDefinition[] = [
  {
    id: 'plain',
    label: 'Plain Weave',
    summary: 'Balanced over-under repeat with a stable checker drawdown.',
    document: normalizeDraft({
      version: 1,
      sourceType: 'manual',
      shaftCount: 4,
      treadleCount: 4,
      threading: [1, 2, 3, 4, 1, 2, 3, 4],
      tieUp: [
        [true, false, true, false],
        [false, true, false, true],
        [true, false, true, false],
        [false, true, false, true],
      ],
      treadling: [1, 2, 1, 2, 1, 2, 1, 2],
      warpColors: ['#f1ead9'],
      weftColors: ['#af5f3f'],
      parseConfidence: 1,
      warnings: [],
      title: 'Plain Weave',
      sourceLabel: 'Preset',
    }),
  },
  {
    id: 'basket',
    label: 'Basket Weave',
    summary: 'Grouped ends and picks create paired over-under blocks.',
    document: normalizeDraft({
      version: 1,
      sourceType: 'manual',
      shaftCount: 4,
      treadleCount: 4,
      threading: [1, 1, 2, 2, 3, 3, 4, 4],
      tieUp: [
        [true, false, false, false],
        [true, false, false, false],
        [false, true, false, false],
        [false, true, false, false],
      ],
      treadling: [1, 1, 2, 2, 1, 1, 2, 2],
      warpColors: ['#e8dbc2'],
      weftColors: ['#8d4c33'],
      parseConfidence: 1,
      warnings: [],
      title: 'Basket Weave',
      sourceLabel: 'Preset',
    }),
  },
  {
    id: 'twill',
    label: '2/2 Twill',
    summary: 'Classic diagonal twill progression across four shafts.',
    document: normalizeDraft({
      version: 1,
      sourceType: 'manual',
      shaftCount: 4,
      treadleCount: 4,
      threading: [1, 2, 3, 4, 1, 2, 3, 4],
      tieUp: [
        [true, false, false, true],
        [true, true, false, false],
        [false, true, true, false],
        [false, false, true, true],
      ],
      treadling: [1, 2, 3, 4, 1, 2, 3, 4],
      warpColors: ['#f6ebda'],
      weftColors: ['#c46538'],
      parseConfidence: 1,
      warnings: [],
      title: '2/2 Twill',
      sourceLabel: 'Preset',
    }),
  },
  {
    id: 'satin',
    label: '5-End Satin',
    summary: 'Longer floats with a smoother, more lustrous surface pattern.',
    document: normalizeDraft({
      version: 1,
      sourceType: 'manual',
      shaftCount: 5,
      treadleCount: 5,
      threading: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
      tieUp: [
        [true, false, false, false, false],
        [false, false, true, false, false],
        [false, false, false, false, true],
        [false, true, false, false, false],
        [false, false, false, true, false],
      ],
      treadling: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
      warpColors: ['#f5eee1'],
      weftColors: ['#b75a2c'],
      parseConfidence: 1,
      warnings: [],
      title: '5-End Satin',
      sourceLabel: 'Preset',
    }),
  },
  {
    id: 'warp-rib',
    label: 'Warp Rib',
    summary: 'Dense warp grouping with restrained treadling for bold ribs.',
    document: normalizeDraft({
      version: 1,
      sourceType: 'manual',
      shaftCount: 4,
      treadleCount: 4,
      threading: [1, 1, 2, 2, 3, 3, 4, 4],
      tieUp: [
        [true, false, false, false],
        [false, false, true, false],
        [false, true, false, false],
        [false, false, false, true],
      ],
      treadling: [1, 1, 1, 2, 2, 2, 3, 3],
      warpColors: ['#efe7d7'],
      weftColors: ['#975737'],
      parseConfidence: 1,
      warnings: [],
      title: 'Warp Rib',
      sourceLabel: 'Preset',
    }),
  },
];
